### PR TITLE
Debugging & access_log ${ACCESS_LOG} main; issue

### PR DESCRIPTION
**Pull request by ckotte**
- added debug variable to docker-entrypoint.sh
- fixed configuration error when using DISABLE_ACCESS_LOG="true"

### CODE REVIEW

**Comment by blacklabelops** [comment]
What's the Access-Log-Issue? All I can see is that `DISABLE_ACCESS_LOG` seems to disable the access log format `main`. It does not disable the log itself.

**Comment by ckotte** [comment]
I get the error "nginx: [emerg] invalid parameter "main" in /etc/nginx/nginx.conf:11" and NGINX container is constantly restarting. 

> http {
>   log_format  main  '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
> 
>   access_log off main;

Looks like the access log can only be disabled globally; access_log off works.

**Comment by blacklabelops** [comment]
Weird. I tried and can't reproduce this.

My command:

~~~~
docker run -d \
    -p 80:80 \
    --name nginx \
    -e "SERVER1REVERSE_PROXY_LOCATION1=/" \
    -e "SERVER1REVERSE_PROXY_PASS1=http://www.heise.de/" \
    blacklabelops/nginx
~~~~

**Comment by ckotte** [comment]
you need to use DISABLE_ACCESS_LOG="true"

**Comment by blacklabelops** [comment]
Ah, now i understand the problem.

**Comment by blacklabelops** [comment]
Thank you for the correction!

**Pull request merged**
